#ifndef EXAMPLE_READER_H
#define EXAMPLE_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct example_Person_table *example_Person_table_t;
typedef struct example_Person_table *example_Person_mutable_table_t;
typedef const flatbuffers_uoffset_t *example_Person_vec_t;
typedef flatbuffers_uoffset_t *example_Person_mutable_vec_t;
#ifndef example_Person_file_identifier
#define example_Person_file_identifier flatbuffers_identifier
#endif
/* deprecated, use example_Person_file_identifier */
#ifndef example_Person_identifier
#define example_Person_identifier flatbuffers_identifier
#endif
#define example_Person_type_hash ((flatbuffers_thash_t)0x5bea1eb8)
#define example_Person_type_identifier "\xb8\x1e\xea\x5b"



struct example_Person_table { uint8_t unused__; };

static inline size_t example_Person_vec_len(example_Person_vec_t vec)
__flatbuffers_vec_len(vec)
static inline example_Person_table_t example_Person_vec_at(example_Person_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(example_Person_table_t, vec, i, 0)
__flatbuffers_table_as_root(example_Person)

__flatbuffers_define_string_field(0, example_Person, name, 0)
__flatbuffers_define_scalar_field(1, example_Person, id, flatbuffers_int32, int32_t, INT32_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* EXAMPLE_READER_H */
