// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grid.proto
// Protobuf C++ Version: 5.29.3

#include "grid.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace grid {

inline constexpr ShapeDetails::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : width_{0},
        height_{0},
        length_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ShapeDetails::ShapeDetails(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ShapeDetailsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShapeDetailsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShapeDetailsDefaultTypeInternal() {}
  union {
    ShapeDetails _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShapeDetailsDefaultTypeInternal _ShapeDetails_default_instance_;

inline constexpr Star::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : star_details_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Star::Star(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StarDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StarDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StarDefaultTypeInternal() {}
  union {
    Star _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StarDefaultTypeInternal _Star_default_instance_;

inline constexpr Square::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        square_details_{nullptr},
        number_of_squares_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Square::Square(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SquareDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SquareDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SquareDefaultTypeInternal() {}
  union {
    Square _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SquareDefaultTypeInternal _Square_default_instance_;

inline constexpr Shapes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : many_shapes_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Shapes::Shapes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ShapesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShapesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShapesDefaultTypeInternal() {}
  union {
    Shapes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShapesDefaultTypeInternal _Shapes_default_instance_;
}  // namespace grid
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_grid_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_grid_2eproto = nullptr;
const ::uint32_t
    TableStruct_grid_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::grid::ShapeDetails, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::grid::ShapeDetails, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::grid::ShapeDetails, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::grid::ShapeDetails, _impl_.length_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::grid::Star, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::grid::Star, _impl_.star_details_),
        PROTOBUF_FIELD_OFFSET(::grid::Square, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::grid::Square, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::grid::Square, _impl_.square_details_),
        PROTOBUF_FIELD_OFFSET(::grid::Square, _impl_.number_of_squares_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::grid::Shapes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::grid::Shapes, _impl_.many_shapes_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::grid::ShapeDetails)},
        {11, -1, -1, sizeof(::grid::Star)},
        {20, 30, -1, sizeof(::grid::Square)},
        {32, -1, -1, sizeof(::grid::Shapes)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::grid::_ShapeDetails_default_instance_._instance,
    &::grid::_Star_default_instance_._instance,
    &::grid::_Square_default_instance_._instance,
    &::grid::_Shapes_default_instance_._instance,
};
const char descriptor_table_protodef_grid_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ngrid.proto\022\004grid\"=\n\014ShapeDetails\022\r\n\005wi"
    "dth\030\001 \001(\001\022\016\n\006height\030\002 \001(\001\022\016\n\006length\030\003 \001("
    "\001\"0\n\004Star\022(\n\014star_details\030\001 \003(\0132\022.grid.S"
    "hapeDetails\"O\n\006Square\022*\n\016square_details\030"
    "\001 \001(\0132\022.grid.ShapeDetails\022\031\n\021number_of_s"
    "quares\030\002 \001(\001\"1\n\006Shapes\022\'\n\013many_shapes\030\001 "
    "\003(\0132\022.grid.ShapeDetailsb\006proto3"
};
static ::absl::once_flag descriptor_table_grid_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_grid_2eproto = {
    false,
    false,
    271,
    descriptor_table_protodef_grid_2eproto,
    "grid.proto",
    &descriptor_table_grid_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_grid_2eproto::offsets,
    file_level_enum_descriptors_grid_2eproto,
    file_level_service_descriptors_grid_2eproto,
};
namespace grid {
// ===================================================================

class ShapeDetails::_Internal {
 public:
};

ShapeDetails::ShapeDetails(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grid.ShapeDetails)
}
ShapeDetails::ShapeDetails(
    ::google::protobuf::Arena* arena, const ShapeDetails& from)
    : ShapeDetails(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ShapeDetails::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ShapeDetails::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, length_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::length_));
}
ShapeDetails::~ShapeDetails() {
  // @@protoc_insertion_point(destructor:grid.ShapeDetails)
  SharedDtor(*this);
}
inline void ShapeDetails::SharedDtor(MessageLite& self) {
  ShapeDetails& this_ = static_cast<ShapeDetails&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ShapeDetails::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ShapeDetails(arena);
}
constexpr auto ShapeDetails::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ShapeDetails),
                                            alignof(ShapeDetails));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ShapeDetails::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ShapeDetails_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ShapeDetails::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ShapeDetails>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ShapeDetails::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ShapeDetails>(), &ShapeDetails::ByteSizeLong,
            &ShapeDetails::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_._cached_size_),
        false,
    },
    &ShapeDetails::kDescriptorMethods,
    &descriptor_table_grid_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ShapeDetails::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ShapeDetails::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::grid::ShapeDetails>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double width = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.width_)}},
    // double height = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.height_)}},
    // double length = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.length_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double width = 1;
    {PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.width_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double height = 2;
    {PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double length = 3;
    {PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.length_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ShapeDetails::Clear() {
// @@protoc_insertion_point(message_clear_start:grid.ShapeDetails)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.width_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.length_) -
      reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.length_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ShapeDetails::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ShapeDetails& this_ = static_cast<const ShapeDetails&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ShapeDetails::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ShapeDetails& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:grid.ShapeDetails)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double width = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_width()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_width(), target);
          }

          // double height = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_height()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_height(), target);
          }

          // double length = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_length()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_length(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:grid.ShapeDetails)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ShapeDetails::ByteSizeLong(const MessageLite& base) {
          const ShapeDetails& this_ = static_cast<const ShapeDetails&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ShapeDetails::ByteSizeLong() const {
          const ShapeDetails& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:grid.ShapeDetails)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double width = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_width()) != 0) {
              total_size += 9;
            }
            // double height = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_height()) != 0) {
              total_size += 9;
            }
            // double length = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_length()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ShapeDetails::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ShapeDetails*>(&to_msg);
  auto& from = static_cast<const ShapeDetails&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grid.ShapeDetails)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_width()) != 0) {
    _this->_impl_.width_ = from._impl_.width_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_height()) != 0) {
    _this->_impl_.height_ = from._impl_.height_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_length()) != 0) {
    _this->_impl_.length_ = from._impl_.length_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ShapeDetails::CopyFrom(const ShapeDetails& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grid.ShapeDetails)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ShapeDetails::InternalSwap(ShapeDetails* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.length_)
      + sizeof(ShapeDetails::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(ShapeDetails, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata ShapeDetails::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Star::_Internal {
 public:
};

Star::Star(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grid.Star)
}
inline PROTOBUF_NDEBUG_INLINE Star::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::grid::Star& from_msg)
      : star_details_{visibility, arena, from.star_details_},
        _cached_size_{0} {}

Star::Star(
    ::google::protobuf::Arena* arena,
    const Star& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Star* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:grid.Star)
}
inline PROTOBUF_NDEBUG_INLINE Star::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : star_details_{visibility, arena},
        _cached_size_{0} {}

inline void Star::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Star::~Star() {
  // @@protoc_insertion_point(destructor:grid.Star)
  SharedDtor(*this);
}
inline void Star::SharedDtor(MessageLite& self) {
  Star& this_ = static_cast<Star&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Star::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Star(arena);
}
constexpr auto Star::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Star, _impl_.star_details_) +
          decltype(Star::_impl_.star_details_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Star), alignof(Star), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Star::PlacementNew_,
                                 sizeof(Star),
                                 alignof(Star));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Star::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Star_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Star::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Star>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Star::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Star>(), &Star::ByteSizeLong,
            &Star::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Star, _impl_._cached_size_),
        false,
    },
    &Star::kDescriptorMethods,
    &descriptor_table_grid_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Star::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Star::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::grid::Star>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .grid.ShapeDetails star_details = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Star, _impl_.star_details_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .grid.ShapeDetails star_details = 1;
    {PROTOBUF_FIELD_OFFSET(Star, _impl_.star_details_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::grid::ShapeDetails>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Star::Clear() {
// @@protoc_insertion_point(message_clear_start:grid.Star)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.star_details_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Star::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Star& this_ = static_cast<const Star&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Star::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Star& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:grid.Star)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .grid.ShapeDetails star_details = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_star_details_size());
               i < n; i++) {
            const auto& repfield = this_._internal_star_details().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:grid.Star)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Star::ByteSizeLong(const MessageLite& base) {
          const Star& this_ = static_cast<const Star&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Star::ByteSizeLong() const {
          const Star& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:grid.Star)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .grid.ShapeDetails star_details = 1;
            {
              total_size += 1UL * this_._internal_star_details_size();
              for (const auto& msg : this_._internal_star_details()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Star::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Star*>(&to_msg);
  auto& from = static_cast<const Star&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grid.Star)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_star_details()->MergeFrom(
      from._internal_star_details());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Star::CopyFrom(const Star& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grid.Star)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Star::InternalSwap(Star* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.star_details_.InternalSwap(&other->_impl_.star_details_);
}

::google::protobuf::Metadata Star::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Square::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Square>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Square, _impl_._has_bits_);
};

Square::Square(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grid.Square)
}
inline PROTOBUF_NDEBUG_INLINE Square::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::grid::Square& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Square::Square(
    ::google::protobuf::Arena* arena,
    const Square& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Square* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.square_details_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::grid::ShapeDetails>(
                              arena, *from._impl_.square_details_)
                        : nullptr;
  _impl_.number_of_squares_ = from._impl_.number_of_squares_;

  // @@protoc_insertion_point(copy_constructor:grid.Square)
}
inline PROTOBUF_NDEBUG_INLINE Square::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Square::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, square_details_),
           0,
           offsetof(Impl_, number_of_squares_) -
               offsetof(Impl_, square_details_) +
               sizeof(Impl_::number_of_squares_));
}
Square::~Square() {
  // @@protoc_insertion_point(destructor:grid.Square)
  SharedDtor(*this);
}
inline void Square::SharedDtor(MessageLite& self) {
  Square& this_ = static_cast<Square&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.square_details_;
  this_._impl_.~Impl_();
}

inline void* Square::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Square(arena);
}
constexpr auto Square::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Square),
                                            alignof(Square));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Square::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Square_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Square::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Square>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Square::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Square>(), &Square::ByteSizeLong,
            &Square::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Square, _impl_._cached_size_),
        false,
    },
    &Square::kDescriptorMethods,
    &descriptor_table_grid_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Square::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Square::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Square, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::grid::Square>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double number_of_squares = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Square, _impl_.number_of_squares_)}},
    // .grid.ShapeDetails square_details = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Square, _impl_.square_details_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .grid.ShapeDetails square_details = 1;
    {PROTOBUF_FIELD_OFFSET(Square, _impl_.square_details_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // double number_of_squares = 2;
    {PROTOBUF_FIELD_OFFSET(Square, _impl_.number_of_squares_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }}, {{
    {::_pbi::TcParser::GetTable<::grid::ShapeDetails>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Square::Clear() {
// @@protoc_insertion_point(message_clear_start:grid.Square)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.square_details_ != nullptr);
    _impl_.square_details_->Clear();
  }
  _impl_.number_of_squares_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Square::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Square& this_ = static_cast<const Square&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Square::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Square& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:grid.Square)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .grid.ShapeDetails square_details = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.square_details_, this_._impl_.square_details_->GetCachedSize(), target,
                stream);
          }

          // double number_of_squares = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_number_of_squares()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_number_of_squares(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:grid.Square)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Square::ByteSizeLong(const MessageLite& base) {
          const Square& this_ = static_cast<const Square&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Square::ByteSizeLong() const {
          const Square& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:grid.Square)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .grid.ShapeDetails square_details = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.square_details_);
            }
          }
           {
            // double number_of_squares = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_number_of_squares()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Square::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Square*>(&to_msg);
  auto& from = static_cast<const Square&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:grid.Square)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.square_details_ != nullptr);
    if (_this->_impl_.square_details_ == nullptr) {
      _this->_impl_.square_details_ =
          ::google::protobuf::Message::CopyConstruct<::grid::ShapeDetails>(arena, *from._impl_.square_details_);
    } else {
      _this->_impl_.square_details_->MergeFrom(*from._impl_.square_details_);
    }
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_number_of_squares()) != 0) {
    _this->_impl_.number_of_squares_ = from._impl_.number_of_squares_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Square::CopyFrom(const Square& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grid.Square)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Square::InternalSwap(Square* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Square, _impl_.number_of_squares_)
      + sizeof(Square::_impl_.number_of_squares_)
      - PROTOBUF_FIELD_OFFSET(Square, _impl_.square_details_)>(
          reinterpret_cast<char*>(&_impl_.square_details_),
          reinterpret_cast<char*>(&other->_impl_.square_details_));
}

::google::protobuf::Metadata Square::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Shapes::_Internal {
 public:
};

Shapes::Shapes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:grid.Shapes)
}
inline PROTOBUF_NDEBUG_INLINE Shapes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::grid::Shapes& from_msg)
      : many_shapes_{visibility, arena, from.many_shapes_},
        _cached_size_{0} {}

Shapes::Shapes(
    ::google::protobuf::Arena* arena,
    const Shapes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Shapes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:grid.Shapes)
}
inline PROTOBUF_NDEBUG_INLINE Shapes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : many_shapes_{visibility, arena},
        _cached_size_{0} {}

inline void Shapes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Shapes::~Shapes() {
  // @@protoc_insertion_point(destructor:grid.Shapes)
  SharedDtor(*this);
}
inline void Shapes::SharedDtor(MessageLite& self) {
  Shapes& this_ = static_cast<Shapes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Shapes::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Shapes(arena);
}
constexpr auto Shapes::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Shapes, _impl_.many_shapes_) +
          decltype(Shapes::_impl_.many_shapes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Shapes), alignof(Shapes), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Shapes::PlacementNew_,
                                 sizeof(Shapes),
                                 alignof(Shapes));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Shapes::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Shapes_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Shapes::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Shapes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Shapes::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Shapes>(), &Shapes::ByteSizeLong,
            &Shapes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Shapes, _impl_._cached_size_),
        false,
    },
    &Shapes::kDescriptorMethods,
    &descriptor_table_grid_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Shapes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Shapes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::grid::Shapes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .grid.ShapeDetails many_shapes = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Shapes, _impl_.many_shapes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .grid.ShapeDetails many_shapes = 1;
    {PROTOBUF_FIELD_OFFSET(Shapes, _impl_.many_shapes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::grid::ShapeDetails>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Shapes::Clear() {
// @@protoc_insertion_point(message_clear_start:grid.Shapes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.many_shapes_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Shapes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Shapes& this_ = static_cast<const Shapes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Shapes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Shapes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:grid.Shapes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .grid.ShapeDetails many_shapes = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_many_shapes_size());
               i < n; i++) {
            const auto& repfield = this_._internal_many_shapes().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:grid.Shapes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Shapes::ByteSizeLong(const MessageLite& base) {
          const Shapes& this_ = static_cast<const Shapes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Shapes::ByteSizeLong() const {
          const Shapes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:grid.Shapes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .grid.ShapeDetails many_shapes = 1;
            {
              total_size += 1UL * this_._internal_many_shapes_size();
              for (const auto& msg : this_._internal_many_shapes()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Shapes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Shapes*>(&to_msg);
  auto& from = static_cast<const Shapes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grid.Shapes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_many_shapes()->MergeFrom(
      from._internal_many_shapes());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Shapes::CopyFrom(const Shapes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grid.Shapes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Shapes::InternalSwap(Shapes* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.many_shapes_.InternalSwap(&other->_impl_.many_shapes_);
}

::google::protobuf::Metadata Shapes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grid
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_grid_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
