#ifndef EXAMPLE_BUILDER_H
#define EXAMPLE_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef EXAMPLE_READER_H
#include "example_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

static const flatbuffers_voffset_t __example_Person_required[] = { 0 };
typedef flatbuffers_ref_t example_Person_ref_t;
static example_Person_ref_t example_Person_clone(flatbuffers_builder_t *B, example_Person_table_t t);
__flatbuffers_build_table(flatbuffers_, example_Person, 2)

#define __example_Person_formal_args , flatbuffers_string_ref_t v0, int32_t v1
#define __example_Person_call_args , v0, v1
static inline example_Person_ref_t example_Person_create(flatbuffers_builder_t *B __example_Person_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, example_Person, example_Person_file_identifier, example_Person_type_identifier)

__flatbuffers_build_string_field(0, flatbuffers_, example_Person_name, example_Person)
__flatbuffers_build_scalar_field(1, flatbuffers_, example_Person_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), example_Person)

static inline example_Person_ref_t example_Person_create(flatbuffers_builder_t *B __example_Person_formal_args)
{
    if (example_Person_start(B)
        || example_Person_name_add(B, v0)
        || example_Person_id_add(B, v1)) {
        return 0;
    }
    return example_Person_end(B);
}

static example_Person_ref_t example_Person_clone(flatbuffers_builder_t *B, example_Person_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (example_Person_start(B)
        || example_Person_name_pick(B, t)
        || example_Person_id_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, example_Person_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* EXAMPLE_BUILDER_H */
